// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopWebApllication.Data;

namespace ShopWebApllication.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20220411200304_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FurniturePurchase", b =>
                {
                    b.Property<string>("furnituresid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("purchasesid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("furnituresid", "purchasesid");

                    b.HasIndex("purchasesid");

                    b.ToTable("FurniturePurchase");
                });

            modelBuilder.Entity("ShopWebApllication.Data.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShopWebApllication.Data.Furniture", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("categoryid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("inStock")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("categoryid");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("ShopWebApllication.Data.Models.Purchase", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FurniturePurchase", b =>
                {
                    b.HasOne("ShopWebApllication.Data.Furniture", null)
                        .WithMany()
                        .HasForeignKey("furnituresid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopWebApllication.Data.Models.Purchase", null)
                        .WithMany()
                        .HasForeignKey("purchasesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopWebApllication.Data.Furniture", b =>
                {
                    b.HasOne("ShopWebApllication.Data.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryid");

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
